---
- name: Ensure required packages are installed
  apt:
    name:
      - open-iscsi
      - nfs-common
      - cryptsetup
    state: present
    update_cache: yes

- name: Ensure containerd is enabled and started
  systemd:
    name: iscsid
    enabled: yes
    state: started

- name: Add the iscsi_tcp module
  community.general.modprobe:
    name: iscsi_tcp
    state: present

- name: Pause for 1 minute
  ansible.builtin.pause:
    minutes: 1
