---
# tasks file for containerd
- name: Ensure required packages are installed
  apt:
    name:
      - apt-transport-https
      - curl
      - gpg
    state: present
    update_cache: yes

- name: Create an empty file for the containerd module
  copy:
    content: ""
    dest: /etc/modules-load.d/containerd.conf
    force: no

- name: Configure modules for containerd
  blockinfile:
    path: /etc/modules-load.d/containerd.conf
    block: |
      overlay
      br_netfilter

- name: Add Docker APT GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present
    filename: "docker"

- name: Run apt-get update and install docker packages
  apt:
    update_cache: true
    name:
      - docker
      - docker-ce
      - containerd.io
  become: true

- name: Ensure /etc/containerd directory exists
  file:
    path: /etc/containerd
    state: directory
    mode: "0755"

- name: Generate containerd default config and save to /etc/containerd/config.toml
  command: containerd config default
  register: containerd_config

- name: Write containerd config to /etc/containerd/config.toml
  copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml
    mode: "0644"

- name: Ensure containerd is enabled and started
  systemd:
    name: containerd
    enabled: yes
    state: started

- name: Ensure docker is enabled and started
  systemd:
    name: docker
    enabled: yes
    state: started
