Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux" #archlinux/archlinux debian/bookworm64 "archlinux/archlinux"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end
